export const questions = [
  {
    question: "Sebutkan makanan yang biasa dijual di pinggir jalan!",
    answers: [
      { text: "nasi goreng", points: 35 },
      { text: "mie goreng", points: 25 },
      { text: "sate", points: 20 },
      { text: "bakso", points: 15 },
      { text: "martabak", points: 10 },
      { text: "gorengan", points: 5 },
      { text: "siomay", points: 5 },
    ],
  },
  {
    question: "Sebutkan profesi yang sering ditemui di rumah sakit!",
    answers: [
      { text: "dokter", points: 35 },
      { text: "perawat", points: 30 },
      { text: "apoteker", points: 15 },
      { text: "satpam", points: 10 },
      { text: "cleaning service", points: 5 },
      { text: "administrasi", points: 5 },
      { text: "laboran", points: 5 },
    ],
  },
  {
    question: "Apa yang biasa dilakukan orang saat macet?",
    answers: [
      { text: "main hp", points: 40 },
      { text: "klakson", points: 25 },
      { text: "ngomel", points: 20 },
      { text: "tidur", points: 10 },
      { text: "dengerin musik", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang biasa ada di dalam tas perempuan!",
    answers: [
      { text: "dompet", points: 30 },
      { text: "hp", points: 25 },
      { text: "makeup", points: 20 },
      { text: "tisu", points: 10 },
      { text: "sisir", points: 5 },
      { text: "powerbank", points: 5 },
      { text: "parfum", points: 5 },
    ],
  },
  {
    question: "Sebutkan alasan telat masuk kerja/sekolah!",
    answers: [
      { text: "macet", points: 35 },
      { text: "bangun kesiangan", points: 30 },
      { text: "ban bocor", points: 15 },
      { text: "hujan", points: 10 },
      { text: "ketinggalan kendaraan", points: 5 },
      { text: "lupa set alarm", points: 5 },
    ],
  },
  {
    question: "Sebutkan tempat yang sering dijadikan lokasi kencan pertama!",
    answers: [
      { text: "cafe", points: 35 },
      { text: "bioskop", points: 30 },
      { text: "mall", points: 20 },
      { text: "taman", points: 10 },
      { text: "restoran", points: 5 },
      { text: "pantai", points: 5 },
    ],
  },
  {
    question: "Apa yang biasa dibawa saat piknik?",
    answers: [
      { text: "makanan", points: 30 },
      { text: "minuman", points: 25 },
      { text: "tikar", points: 20 },
      { text: "kamera", points: 10 },
      { text: "topi", points: 5 },
      { text: "sunblock", points: 5 },
      { text: "games atau buku", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang biasa dilakukan orang sebelum tidur!",
    answers: [
      { text: "main hp", points: 35 },
      { text: "gosok gigi", points: 25 },
      { text: "cuci muka", points: 20 },
      { text: "doa", points: 10 },
      { text: "pasang alarm", points: 5 },
      { text: "baca buku", points: 5 },
    ],
  },
  {
    question: "Sebutkan aplikasi sosial media yang populer!",
    answers: [
      { text: "whatsapp", points: 30 },
      { text: "instagram", points: 25 },
      { text: "tiktok", points: 20 },
      { text: "facebook", points: 15 },
      { text: "twitter", points: 10 },
      { text: "snapchat", points: 5 },
    ],
  },
  {
    question: "Apa yang biasa dikatakan orang tua saat anak minta uang jajan?",
    answers: [
      { text: "masih ada kemarin", points: 35 },
      { text: "nabung", points: 30 },
      { text: "boros", points: 20 },
      { text: "tunggu gajian", points: 10 },
      { text: "udah banyak", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang biasa dipakai saat hujan!",
    answers: [
      { text: "payung", points: 40 },
      { text: "jas hujan", points: 30 },
      { text: "sepatu boots", points: 15 },
      { text: "mantel", points: 10 },
      { text: "topi", points: 5 },
    ],
  },
  {
    question: "Sebutkan kegiatan yang biasa dilakukan saat weekend!",
    answers: [
      { text: "jalan-jalan", points: 30 },
      { text: "nonton film", points: 25 },
      { text: "tidur", points: 20 },
      { text: "olahraga", points: 15 },
      { text: "belanja", points: 10 },
    ],
  },
  {
    question: "Sebutkan alasan orang pergi ke gym!",
    answers: [
      { text: "menurunkan berat badan", points: 35 },
      { text: "membentuk otot", points: 30 },
      { text: "kesehatan", points: 20 },
      { text: "mengisi waktu luang", points: 10 },
      { text: "ikut teman", points: 5 },
    ],
  },
  {
    question: "Sebutkan alat yang digunakan untuk berkebun!",
    answers: [
      { text: "cangkul", points: 30 },
      { text: "sekop", points: 25 },
      { text: "gunting tanaman", points: 20 },
      { text: "selang", points: 15 },
      { text: "pot", points: 10 },
    ],
  },
  {
    question: "Sebutkan aktivitas yang biasa dilakukan di pantai!",
    answers: [
      { text: "berenang", points: 35 },
      { text: "berjemur", points: 25 },
      { text: "main pasir", points: 20 },
      { text: "surfing", points: 10 },
      { text: "piknik", points: 10 },
    ],
  },
  {
    question: "Sebutkan hewan yang biasa dipelihara di rumah!",
    answers: [
      { text: "kucing", points: 40 },
      { text: "anjing", points: 30 },
      { text: "ikan", points: 15 },
      { text: "burung", points: 10 },
      { text: "kelinci", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat listrik mati!",
    answers: [
      { text: "lilin", points: 35 },
      { text: "senter", points: 30 },
      { text: "power bank", points: 15 },
      { text: "korek api", points: 10 },
      { text: "lampu darurat", points: 10 },
    ],
  },
  {
    question: "Sebutkan benda yang sering ada di meja kerja!",
    answers: [
      { text: "laptop", points: 40 },
      { text: "buku catatan", points: 20 },
      { text: "pena", points: 15 },
      { text: "stapler", points: 10 },
      { text: "mouse", points: 10 },
      { text: "cangkir kopi", points: 5 },
    ],
  },
  {
    question: "Sebutkan buah yang sering dijadikan jus!",
    answers: [
      { text: "jeruk", points: 30 },
      { text: "mangga", points: 25 },
      { text: "alpukat", points: 20 },
      { text: "melon", points: 10 },
      { text: "pisang", points: 10 },
      { text: "stroberi", points: 5 },
    ],
  },
  {
    question: "Sebutkan alat yang biasa digunakan untuk memasak!",
    answers: [
      { text: "kompor", points: 35 },
      { text: "wajan", points: 30 },
      { text: "pisau", points: 15 },
      { text: "sendok kayu", points: 10 },
      { text: "panci", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan sebelum tidur!",
    answers: [
      { text: "gosok gigi", points: 35 },
      { text: "cuci muka", points: 25 },
      { text: "berdoa", points: 20 },
      { text: "cek ponsel", points: 15 },
      { text: "minum air", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering ketinggalan saat bepergian!",
    answers: [
      { text: "dompet", points: 35 },
      { text: "kunci", points: 30 },
      { text: "ponsel", points: 20 },
      { text: "power bank", points: 10 },
      { text: "jaket", points: 5 },
    ],
  },
  {
    question: "Sebutkan alasan orang bangun kesiangan!",
    answers: [
      { text: "tidur terlalu malam", points: 40 },
      { text: "alarm tidak berbunyi", points: 25 },
      { text: "mati lampu", points: 15 },
      { text: "kelelahan", points: 10 },
      { text: "tidak ada yang membangunkan", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang biasanya ada di dalam kulkas!",
    answers: [
      { text: "telur", points: 30 },
      { text: "susu", points: 25 },
      { text: "sayur", points: 20 },
      { text: "buah", points: 15 },
      { text: "air dingin", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dibawa saat hujan!",
    answers: [
      { text: "payung", points: 40 },
      { text: "jas hujan", points: 30 },
      { text: "sendal", points: 15 },
      { text: "handuk kecil", points: 10 },
      { text: "topi", points: 5 },
    ],
  },
  {
    question: "Sebutkan alat elektronik yang ada di dapur!",
    answers: [
      { text: "rice cooker", points: 35 },
      { text: "blender", points: 30 },
      { text: "kulkas", points: 20 },
      { text: "oven", points: 10 },
      { text: "microwave", points: 5 },
    ],
  },
  {
    question: "Sebutkan kegiatan yang sering dilakukan saat liburan!",
    answers: [
      { text: "jalan-jalan", points: 35 },
      { text: "berenang", points: 25 },
      { text: "berkemah", points: 15 },
      { text: "mengunjungi keluarga", points: 15 },
      { text: "belanja", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat lapar di malam hari!",
    answers: [
      { text: "mie instan", points: 40 },
      { text: "nasi goreng", points: 25 },
      { text: "roti", points: 15 },
      { text: "gorengan", points: 10 },
      { text: "susu", points: 10 },
    ],
  },
  {
    question: "Sebutkan hal yang sering dilakukan saat bosan!",
    answers: [
      { text: "main HP", points: 35 },
      { text: "nonton TV", points: 25 },
      { text: "tidur", points: 15 },
      { text: "mendengarkan musik", points: 15 },
      { text: "makan", points: 10 },
    ],
  },
  {
    question: "Sebutkan barang yang sering hilang di rumah!",
    answers: [
      { text: "remote TV", points: 40 },
      { text: "kunci", points: 30 },
      { text: "ponsel", points: 15 },
      { text: "dompet", points: 10 },
      { text: "kacamata", points: 5 },
    ],
  },
  {
    question: "Sebutkan tempat yang sering macet!",
    answers: [
      { text: "jalan raya", points: 40 },
      { text: "pasar", points: 30 },
      { text: "perempatan lampu merah", points: 15 },
      { text: "jalan tol", points: 10 },
      { text: "depan sekolah", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering ditemukan di meja makan!",
    answers: [
      { text: "piring", points: 35 },
      { text: "sendok", points: 30 },
      { text: "gelas", points: 20 },
      { text: "tisu", points: 10 },
      { text: "garam", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan di pagi hari!",
    answers: [
      { text: "sarapan", points: 35 },
      { text: "mandi", points: 30 },
      { text: "olahraga", points: 15 },
      { text: "minum kopi", points: 10 },
      { text: "menonton berita", points: 10 },
    ],
  },
  {
    question:
      "Sebutkan sesuatu yang sering ditanyakan oleh kasir di minimarket!",
    answers: [
      { text: "pakai kartu member?", points: 40 },
      { text: "mau sekalian isi pulsa?", points: 30 },
      { text: "butuh kantong plastik?", points: 15 },
      { text: "ada uang pas?", points: 10 },
      { text: "mau bayar pakai apa?", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat menonton film!",
    answers: [
      { text: "popcorn", points: 35 },
      { text: "minuman", points: 30 },
      { text: "remote", points: 15 },
      { text: "selimut", points: 10 },
      { text: "bantal", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat ingin keluar rumah!",
    answers: [
      { text: "kunci", points: 40 },
      { text: "dompet", points: 30 },
      { text: "ponsel", points: 20 },
      { text: "sepatu", points: 5 },
      { text: "jaket", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering terjadi di kantor!",
    answers: [
      { text: "meeting", points: 35 },
      { text: "kerjaan menumpuk", points: 25 },
      { text: "komputer lemot", points: 20 },
      { text: "makan siang bersama", points: 10 },
      { text: "ngopi", points: 10 },
    ],
  },
  {
    question: "Sebutkan alasan seseorang pergi ke salon!",
    answers: [
      { text: "potong rambut", points: 40 },
      { text: "mewarnai rambut", points: 30 },
      { text: "perawatan wajah", points: 15 },
      { text: "cuci rambut", points: 10 },
      { text: "manicure/pedicure", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang bisa pecah!",
    answers: [
      { text: "gelas", points: 40 },
      { text: "piring", points: 30 },
      { text: "telur", points: 15 },
      { text: "lampu", points: 10 },
      { text: "cermin", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang bisa ditemukan di dompet!",
    answers: [
      { text: "uang", points: 40 },
      { text: "kartu ATM", points: 30 },
      { text: "KTP", points: 15 },
      { text: "struk belanja", points: 10 },
      { text: "foto", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan saat menunggu!",
    answers: [
      { text: "main HP", points: 40 },
      { text: "ngobrol", points: 30 },
      { text: "melihat jam", points: 15 },
      { text: "makan camilan", points: 10 },
      { text: "mengeluh", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan saat mengantuk!",
    answers: [
      { text: "minum kopi", points: 35 },
      { text: "mengucek mata", points: 30 },
      { text: "menggerakkan kepala", points: 15 },
      { text: "mencuci muka", points: 10 },
      { text: "mengubah posisi duduk", points: 10 },
    ],
  },
  {
    question: "Sebutkan benda yang sering 'hilang' di rumah!",
    answers: [
      { text: "remote TV", points: 35 },
      { text: "kunci", points: 30 },
      { text: "kacamata", points: 20 },
      { text: "dompet", points: 10 },
      { text: "charger HP", points: 5 },
    ],
  },
  {
    question: "Apa yang orang lakukan saat bosan di toilet?",
    answers: [
      { text: "main HP", points: 40 },
      { text: "baca buku", points: 25 },
      { text: "nyanyi", points: 15 },
      { text: "ngitung ubin", points: 10 },
      { text: "ngobrol sendiri", points: 10 },
    ],
  },
  {
    question: "Sebutkan alasan klasik saat telat masuk kerja!",
    answers: [
      { text: "macet", points: 35 },
      { text: "ban bocor", points: 25 },
      { text: "ketiduran", points: 20 },
      { text: "sakit", points: 15 },
      { text: "banjir", points: 5 },
    ],
  },
  {
    question: "Apa yang biasa dilakukan orang saat listrik mati?",
    answers: [
      { text: "tidur", points: 30 },
      { text: "main HP", points: 25 },
      { text: "ngobrol", points: 20 },
      { text: "main kartu", points: 15 },
      { text: "nyalain lilin", points: 10 },
    ],
  },
  {
    question: "Sebutkan tempat favorit nyamuk hinggap di tubuh!",
    answers: [
      { text: "kaki", points: 35 },
      { text: "tangan", points: 30 },
      { text: "leher", points: 20 },
      { text: "telinga", points: 10 },
      { text: "punggung", points: 5 },
    ],
  },
  {
    question: "Apa yang sering dilakukan orang di depan cermin?",
    answers: [
      { text: "selfie", points: 35 },
      { text: "dandan", points: 30 },
      { text: "ngomong sendiri", points: 20 },
      { text: "nyanyi", points: 10 },
      { text: "joget", points: 5 },
    ],
  },
  {
    question: "Sebutkan alasan klasik saat putus cinta!",
    answers: [
      { text: "tidak cocok", points: 35 },
      { text: "ada orang ketiga", points: 30 },
      { text: "LDR", points: 20 },
      { text: "beda prinsip", points: 10 },
      { text: "fokus karir", points: 5 },
    ],
  },
  {
    question: "Apa yang sering dilakukan orang saat gugup?",
    answers: [
      { text: "gigit kuku", points: 30 },
      { text: "garuk kepala", points: 25 },
      { text: "main HP", points: 20 },
      { text: "gerak-gerak kaki", points: 15 },
      { text: "minum air", points: 10 },
    ],
  },
  {
    question: "Sebutkan hal yang sering dilakukan di mall selain belanja!",
    answers: [
      { text: "nongkrong", points: 35 },
      { text: "makan", points: 30 },
      { text: "nonton", points: 20 },
      { text: "cuci mata", points: 10 },
      { text: "main game", points: 5 },
    ],
  },
  {
    question: "Apa yang sering dijadikan alasan untuk menolak ajakan kencan?",
    answers: [
      { text: "sibuk", points: 35 },
      { text: "sakit", points: 30 },
      { text: "ada acara keluarga", points: 20 },
      { text: "lagi bokek", points: 10 },
      { text: "harus kerja", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang sering dilakukan orang saat menunggu antrian!",
    answers: [
      { text: "main HP", points: 40 },
      { text: "ngobrol", points: 25 },
      { text: "baca", points: 15 },
      { text: "ngemil", points: 10 },
      { text: "tidur", points: 10 },
    ],
  },
  {
    question: "Apa yang sering dijadikan alasan untuk bolos sekolah?",
    answers: [
      { text: "sakit", points: 35 },
      { text: "bangun kesiangan", points: 30 },
      { text: "PR belum selesai", points: 20 },
      { text: "ada acara keluarga", points: 10 },
      { text: "hujan", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang sering dilakukan orang saat sedang diet!",
    answers: [
      { text: "minum air putih", points: 30 },
      { text: "olahraga", points: 25 },
      { text: "makan sayur", points: 20 },
      { text: "puasa", points: 15 },
      { text: "nimbang badan", points: 10 },
    ],
  },
  {
    question: "Apa yang sering dijadikan alasan untuk menunda pekerjaan?",
    answers: [
      { text: "capek", points: 35 },
      { text: "kurang inspirasi", points: 30 },
      { text: "banyak gangguan", points: 20 },
      { text: "lagi mood", points: 10 },
      { text: "butuh kopi dulu", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang sering dilakukan orang saat naik pesawat!",
    answers: [
      { text: "tidur", points: 35 },
      { text: "nonton film", points: 30 },
      { text: "baca", points: 20 },
      { text: "makan", points: 10 },
      { text: "foto-foto", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dicari saat mati lampu!",
    answers: [
      { text: "lilin", points: 35 },
      { text: "senter", points: 30 },
      { text: "HP", points: 20 },
      { text: "colokan", points: 10 },
      { text: "kipas tangan", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering ketinggalan saat bepergian!",
    answers: [
      { text: "HP", points: 30 },
      { text: "dompet", points: 25 },
      { text: "kunci", points: 20 },
      { text: "earphone", points: 15 },
      { text: "charger", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin orang bangun tengah malam!",
    answers: [
      { text: "kebelet pipis", points: 40 },
      { text: "mimpi buruk", points: 25 },
      { text: "nyamuk", points: 20 },
      { text: "suara aneh", points: 10 },
      { text: "haus", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang orang takutkan di rumah kosong!",
    answers: [
      { text: "hantu", points: 50 },
      { text: "maling", points: 30 },
      { text: "suara aneh", points: 15 },
      { text: "lampu kedap-kedip", points: 5 },
      { text: "TV nyala sendiri", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin panik!",
    answers: [
      { text: "HP hilang", points: 40 },
      { text: "dompet ketinggalan", points: 30 },
      { text: "kendaraan mogok", points: 15 },
      { text: "baterai habis", points: 10 },
      { text: "tanggal merah tapi masuk kerja", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dipencet!",
    answers: [
      { text: "remote TV", points: 30 },
      { text: "tombol HP", points: 25 },
      { text: "lift", points: 20 },
      { text: "klakson", points: 15 },
      { text: "jerawat", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin orang tertawa!",
    answers: [
      { text: "lawakan teman", points: 35 },
      { text: "meme lucu", points: 30 },
      { text: "video kocak", points: 20 },
      { text: "kesialan orang", points: 10 },
      { text: "chat typo", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering menyebabkan orang telat!",
    answers: [
      { text: "bangun kesiangan", points: 40 },
      { text: "macet", points: 30 },
      { text: "kendaraan mogok", points: 15 },
      { text: "hujan", points: 10 },
      { text: "kelamaan pilih baju", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan remaja sebelum tidur!",
    answers: [
      { text: "main HP", points: 50 },
      { text: "scroll TikTok", points: 30 },
      { text: "chatting", points: 20 },
      { text: "dengerin musik", points: 15 },
      { text: "merenung mikirin masa depan", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan orang saat sendirian!",
    answers: [
      { text: "nyanyi-nyanyi sendiri", points: 35 },
      { text: "ngomong sama diri sendiri", points: 30 },
      { text: "main HP", points: 25 },
      { text: "ngelamun", points: 15 },
      { text: "joget depan cermin", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering diketik orang di Google!",
    answers: [
      { text: "cara cepat kaya", points: 40 },
      { text: "arti mimpi", points: 35 },
      { text: "resep makanan", points: 25 },
      { text: "lirik lagu", points: 15 },
      { text: "jadwal bola", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin orang malas bangun pagi!",
    answers: [
      { text: "masih ngantuk", points: 50 },
      { text: "cuaca dingin", points: 30 },
      { text: "tidur terlalu malam", points: 25 },
      { text: "alarm kelewatan", points: 15 },
      { text: "gak ada motivasi", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin orang bad mood!",
    answers: [
      { text: "HP lowbat", points: 40 },
      { text: "cuaca panas", points: 30 },
      { text: "lapar", points: 25 },
      { text: "kena ghosting", points: 15 },
      { text: "terlalu banyak tugas", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan orang saat nunggu!",
    answers: [
      { text: "main HP", points: 50 },
      { text: "scroll media sosial", points: 35 },
      { text: "liatin orang lewat", points: 20 },
      { text: "chat orang random", points: 10 },
      { text: "cek jam tiap 5 detik", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan orang saat di toilet!",
    answers: [
      { text: "main HP", points: 45 },
      { text: "baca chat lama", points: 30 },
      { text: "mikir hal random", points: 20 },
      { text: "nyanyi", points: 10 },
      { text: "kepoin mantan", points: 5 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin orang lupa waktu!",
    answers: [
      { text: "main game", points: 50 },
      { text: "scroll TikTok", points: 35 },
      { text: "nonton series", points: 25 },
      { text: "ngegosip", points: 15 },
      { text: "chatting lama", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering bikin orang kaget!",
    answers: [
      { text: "tagihan internet", points: 40 },
      { text: "HP jatuh", points: 35 },
      { text: "pintu tiba-tiba kebuka", points: 25 },
      { text: "suara notif mantan", points: 15 },
      { text: "kucing lompat tiba-tiba", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dipakai buat alasan telat!",
    answers: [
      { text: "macet", points: 50 },
      { text: "bangun kesiangan", points: 30 },
      { text: "kendaraan mogok", points: 20 },
      { text: "kejebak hujan", points: 15 },
      { text: "lupa set alarm", points: 10 },
    ],
  },
  {
    question: "Sebutkan sesuatu yang sering dilakukan orang saat bosan!",
    answers: [
      { text: "scroll HP", points: 50 },
      { text: "dengerin lagu", points: 35 },
      { text: "iseng gangguin orang", points: 20 },
      { text: "ngemil", points: 15 },
      { text: "liatin langit-langit kamar", points: 10 },
    ],
  },
  {
    question: "Sebutkan makanan yang sering dikonsumsi saat berbuka puasa!",
    answers: [
      { text: "kurma", points: 35 },
      { text: "kolak", points: 30 },
      { text: "es buah", points: 20 },
      { text: "gorengan", points: 15 },
      { text: "sop buah", points: 10 },
      { text: "bubur sumsum", points: 5 },
      { text: "nasi uduk", points: 5 },
    ],
  },
  {
    question: "Apa kebiasaan yang sering dilakukan selama bulan Ramadan?",
    answers: [
      { text: "puasa", points: 35 },
      { text: "taraweh", points: 30 },
      { text: "buka bersama", points: 20 },
      { text: "tadarus Al-Qur'an", points: 15 },
      { text: "sahur", points: 10 },
      { text: "membayar zakat", points: 5 },
      { text: "itkaf", points: 5 },
    ],
  },
  {
    question: "Sebutkan tempat yang sering dikunjungi saat bulan Ramadan!",
    answers: [
      { text: "masjid", points: 35 },
      { text: "pasar takjil", points: 30 },
      { text: "rumah keluarga", points: 20 },
      { text: "restoran", points: 15 },
      { text: "panti asuhan", points: 10 },
      { text: "mall", points: 5 },
      { text: "musala", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang bisa membatalkan puasa!",
    answers: [
      { text: "makan dan minum", points: 35 },
      { text: "marah berlebihan", points: 30 },
      { text: "berhubungan suami istri", points: 20 },
      { text: "muntah disengaja", points: 15 },
      { text: "menstruasi", points: 10 },
      { text: "merokok", points: 5 },
      { text: "berbohong", points: 5 },
    ],
  },
  {
    question: "Sebutkan jenis zakat yang wajib dikeluarkan saat Ramadan!",
    answers: [
      { text: "zakat fitrah", points: 50 },
      { text: "zakat mal", points: 40 },
      { text: "zakat profesi", points: 30 },
      { text: "zakat pertanian", points: 20 },
      { text: "zakat perdagangan", points: 10 },
    ],
  },
  {
    question: "Sebutkan tradisi unik Ramadan di Indonesia!",
    answers: [
      { text: "ngabuburit", points: 35 },
      { text: "padusan", points: 30 },
      { text: "dugderan", points: 25 },
      { text: "malamang", points: 20 },
      { text: "megengan", points: 15 },
      { text: "sahur on the road", points: 10 },
      { text: "takbiran keliling", points: 5 },
    ],
  },
  {
    question: "Apa saja nama bulan dalam kalender Islam?",
    answers: [
      { text: "Muharram", points: 35 },
      { text: "Safar", points: 30 },
      { text: "Rabiul Awal", points: 25 },
      { text: "Rabiul Akhir", points: 20 },
      { text: "Jumadil Awal", points: 15 },
      { text: "Jumadil Akhir", points: 10 },
      { text: "Rajab", points: 5 },
    ],
  },
  {
    question: "Apa nama malam istimewa di bulan Ramadan?",
    answers: [
      { text: "Lailatul Qadar", points: 50 },
      { text: "Nuzulul Quran", points: 40 },
      { text: "Malam Idul Fitri", points: 30 },
      { text: "Malam Nishfu Syaban", points: 20 },
    ],
  },

  // Tema umum
  {
    question: "Sebutkan hewan yang sering dijadikan peliharaan!",
    answers: [
      { text: "kucing", points: 35 },
      { text: "anjing", points: 30 },
      { text: "burung", points: 25 },
      { text: "kelinci", points: 20 },
      { text: "ikan", points: 15 },
      { text: "hamster", points: 10 },
      { text: "iguana", points: 5 },
    ],
  },
  {
    question: "Sebutkan alat musik tradisional Indonesia!",
    answers: [
      { text: "angklung", points: 35 },
      { text: "gamelan", points: 30 },
      { text: "kendang", points: 25 },
      { text: "suling", points: 20 },
      { text: "rebana", points: 15 },
      { text: "sasando", points: 10 },
      { text: "kolintang", points: 5 },
    ],
  },
  {
    question: "Sebutkan jenis olahraga yang populer di Indonesia!",
    answers: [
      { text: "sepak bola", points: 35 },
      { text: "badminton", points: 30 },
      { text: "basket", points: 25 },
      { text: "voli", points: 20 },
      { text: "tenis meja", points: 15 },
      { text: "silat", points: 10 },
      { text: "renang", points: 5 },
    ],
  },
  {
    question: "Sebutkan tempat wisata populer di Indonesia!",
    answers: [
      { text: "Bali", points: 35 },
      { text: "Yogyakarta", points: 30 },
      { text: "Labuan Bajo", points: 25 },
      { text: "Raja Ampat", points: 20 },
      { text: "Danau Toba", points: 15 },
      { text: "Bromo", points: 10 },
      { text: "Lombok", points: 5 },
    ],
  },
  {
    question: "Sebutkan benda yang sering dibawa ke sekolah!",
    answers: [
      { text: "tas", points: 35 },
      { text: "buku", points: 30 },
      { text: "pulpen", points: 25 },
      { text: "penghapus", points: 20 },
      { text: "penggaris", points: 15 },
      { text: "pensil", points: 10 },
      { text: "botol minum", points: 5 },
    ],
  },
  {
    question: "Sebutkan nama warna primer!",
    answers: [
      { text: "merah", points: 35 },
      { text: "biru", points: 30 },
      { text: "kuning", points: 25 },
      { text: "hijau", points: 20 },
      { text: "ungu", points: 15 },
      { text: "jingga", points: 10 },
      { text: "coklat", points: 5 },
    ],
  },
  {
    question: "Sebutkan kegiatan yang dilakukan saat sahur!",
    answers: [
      { text: "makan sahur", points: 35 },
      { text: "minum air putih", points: 30 },
      { text: "sholat tahajud", points: 20 },
      { text: "membaca Al-Qur’an", points: 15 },
      { text: "persiapan puasa", points: 10 },
      { text: "membangunkan keluarga", points: 5 },
      { text: "berdoa", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang dilakukan pada malam takbiran!",
    answers: [
      { text: "takbiran di masjid", points: 35 },
      { text: "konvoi takbiran", points: 30 },
      { text: "menyalakan kembang api", points: 20 },
      { text: "bersiap salat Id", points: 15 },
      { text: "bersih-bersih rumah", points: 10 },
      { text: "memasak ketupat", points: 5 },
      { text: "mengenakan pakaian baru", points: 5 },
    ],
  },
  {
    question: "Sebutkan makanan khas Idul Fitri di Indonesia!",
    answers: [
      { text: "ketupat", points: 35 },
      { text: "opor ayam", points: 30 },
      { text: "rendang", points: 20 },
      { text: "sambal goreng ati", points: 15 },
      { text: "nastar", points: 10 },
      { text: "kastengel", points: 5 },
      { text: "lontong sayur", points: 5 },
    ],
  },
  {
    question: "Apa saja tradisi Idul Fitri di Indonesia?",
    answers: [
      { text: "shalat Idul Fitri", points: 35 },
      { text: "halal bihalal", points: 30 },
      { text: "mudik", points: 20 },
      { text: "bagi-bagi THR", points: 15 },
      { text: "silaturahmi", points: 10 },
      { text: "mengunjungi makam keluarga", points: 5 },
      { text: "bermaaf-maafan", points: 5 },
    ],
  },
  {
    question: "Sebutkan jenis kue kering yang sering ada saat Idul Fitri!",
    answers: [
      { text: "nastar", points: 35 },
      { text: "kastengel", points: 30 },
      { text: "putri salju", points: 20 },
      { text: "sagu keju", points: 15 },
      { text: "lidah kucing", points: 10 },
      { text: "kue semprit", points: 5 },
      { text: "kue kacang", points: 5 },
    ],
  },
  {
    question: "Sebutkan barang yang sering diberikan saat THR!",
    answers: [
      { text: "uang tunai", points: 35 },
      { text: "baju baru", points: 30 },
      { text: "parfum", points: 20 },
      { text: "sarung", points: 15 },
      { text: "sandal", points: 10 },
      { text: "sajadah", points: 5 },
      { text: "mukena", points: 5 },
    ],
  },
  {
    question: "Sebutkan jenis minuman yang sering disajikan saat Lebaran!",
    answers: [
      { text: "sirup", points: 35 },
      { text: "es teh", points: 30 },
      { text: "es buah", points: 20 },
      { text: "air putih", points: 15 },
      { text: "cendol", points: 10 },
      { text: "bandrek", points: 5 },
      { text: "kopi", points: 5 },
    ],
  },
  {
    question: "Sebutkan hal yang dilakukan setelah sholat Idul Fitri!",
    answers: [
      { text: "bermaaf-maafan", points: 35 },
      { text: "silaturahmi ke keluarga", points: 30 },
      { text: "sarapan bersama", points: 20 },
      { text: "mengunjungi makam keluarga", points: 15 },
      { text: "foto keluarga", points: 10 },
      { text: "bagi-bagi THR", points: 5 },
      { text: "mengunjungi tetangga", points: 5 },
    ],
  },
  {
    question: "Sebutkan cabang olahraga yang menggunakan bola!",
    answers: [
      { text: "sepak bola", points: 40 },
      { text: "basket", points: 30 },
      { text: "voli", points: 20 },
      { text: "tenis", points: 15 },
      { text: "futsal", points: 10 },
      { text: "pingpong", points: 5 },
      { text: "rugby", points: 5 },
    ],
  },
  {
    question: "Sebutkan klub sepak bola terkenal di dunia!",
    answers: [
      { text: "Real Madrid", points: 35 },
      { text: "Barcelona", points: 30 },
      { text: "Manchester United", points: 20 },
      { text: "Bayern Munchen", points: 15 },
      { text: "Liverpool", points: 10 },
      { text: "Chelsea", points: 5 },
      { text: "Juventus", points: 5 },
    ],
  },
  {
    question: "Sebutkan pemain sepak bola yang pernah memenangkan Ballon d'Or!",
    answers: [
      { text: "Lionel Messi", points: 40 },
      { text: "Cristiano Ronaldo", points: 35 },
      { text: "Luka Modric", points: 15 },
      { text: "Karim Benzema", points: 10 },
      { text: "Ronaldinho", points: 10 },
      { text: "Zinedine Zidane", points: 5 },
      { text: "Rivaldo", points: 5 },
    ],
  },
  {
    question: "Sebutkan negara yang pernah menjuarai Piala Dunia!",
    answers: [
      { text: "Brasil", points: 40 },
      { text: "Jerman", points: 30 },
      { text: "Italia", points: 25 },
      { text: "Argentina", points: 20 },
      { text: "Prancis", points: 15 },
      { text: "Uruguay", points: 10 },
      { text: "Inggris", points: 5 },
    ],
  },
  {
    question: "Sebutkan klub sepak bola terkenal di dunia!",
    answers: [
      { text: "Real Madrid", points: 35 },
      { text: "Barcelona", points: 30 },
      { text: "Manchester United", points: 20 },
      { text: "Bayern Munchen", points: 15 },
      { text: "Liverpool", points: 10 },
      { text: "Chelsea", points: 5 },
      { text: "Juventus", points: 5 },
    ],
  },
  {
    question: "Sebutkan pemain sepak bola yang pernah memenangkan Ballon d'Or!",
    answers: [
      { text: "Lionel Messi", points: 40 },
      { text: "Cristiano Ronaldo", points: 35 },
      { text: "Luka Modric", points: 15 },
      { text: "Karim Benzema", points: 10 },
      { text: "Ronaldinho", points: 10 },
      { text: "Zinedine Zidane", points: 5 },
      { text: "Rivaldo", points: 5 },
    ],
  },
  {
    question: "Sebutkan negara yang pernah menjuarai Piala Dunia!",
    answers: [
      { text: "Brasil", points: 40 },
      { text: "Jerman", points: 30 },
      { text: "Italia", points: 25 },
      { text: "Argentina", points: 20 },
      { text: "Prancis", points: 15 },
      { text: "Uruguay", points: 10 },
      { text: "Inggris", points: 5 },
    ],
  },
  {
    question: "Sebutkan alasan tim besar tersingkir dari turnamen!",
    answers: [
      { text: "wasit berat sebelah", points: 30 },
      { text: "cedera pemain kunci", points: 25 },
      { text: "gagal penalti", points: 20 },
      { text: "mainnya jelek", points: 15 },
      { text: "kutukan jersey", points: 10 },
      { text: "kesialan", points: 5 },
    ],
  },
  {
    question: "Sebutkan tipe suporter sepak bola!",
    answers: [
      { text: "garis keras", points: 30 },
      { text: "glory hunter", points: 25 },
      { text: "fans dadakan", points: 20 },
      { text: "suporter timnas", points: 15 },
      { text: "haters Messi/Ronaldo", points: 10 },
      { text: "penonton netral", points: 5 },
    ],
  },
  {
    question: "Apa yang sering terjadi di pertandingan final?",
    answers: [
      { text: "drama penalti", points: 30 },
      { text: "gol di menit akhir", points: 25 },
      { text: "VAR bikin kontroversi", points: 20 },
      { text: "tangisan pemain", points: 15 },
      { text: "adu fisik antar pemain", points: 10 },
      { text: "pelatih dipecat setelah kalah", points: 5 },
    ],
  },
  {
    question: "Sebutkan momen ikonik yang pernah diucapkan komentator bola!",
    answers: [
      { text: "Ankara Messi! Ankara Messi!", points: 30 },
      { text: "Allah! Allah! Allah!", points: 25 },
      { text: "More and More and More!", points: 20 },
      { text: "Goal! Goal! Goal!", points: 10 },
    ],
  },
  {
    question: "Siapa GOAT sepak bola saat ini?",
    answers: [
      { text: "Anthony", points: 30 },
      { text: "Harry Maguire", points: 25 },
      { text: "Andre Onana", points: 20 },
      { text: "Darwin Nunez", points: 20 },
      { text: "Mudryk", points: 10 },
      { text: "Nicholas Jackson", points: 10 },
      { text: "Messi", points: 5 },
      { text: "Ronaldo", points: 5 },
      { text: "Neymar", points: 5 },
    ],
  },
];
